// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHk0vOJgz66AZgSCzlA_mX3durKEMzC1w',
    appId: '1:173334404915:web:9c383f7871c6ca2847e846',
    messagingSenderId: '173334404915',
    projectId: 'flutter-firebase-1b98d',
    authDomain: 'flutter-firebase-1b98d.firebaseapp.com',
    storageBucket: 'flutter-firebase-1b98d.firebasestorage.app',
    measurementId: 'G-NTCCSZ17R6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASFbBquKtIb_vEs4wcaY90X0P7mzBWqu8',
    appId: '1:173334404915:android:96106b3ec59f303d47e846',
    messagingSenderId: '173334404915',
    projectId: 'flutter-firebase-1b98d',
    storageBucket: 'flutter-firebase-1b98d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4_6n-v-U1Rzd0J1xHgvyvdqSaaMOiNkw',
    appId: '1:173334404915:ios:93d17190a529f62247e846',
    messagingSenderId: '173334404915',
    projectId: 'flutter-firebase-1b98d',
    storageBucket: 'flutter-firebase-1b98d.firebasestorage.app',
    iosClientId: '173334404915-3jh6inpe7r28mm6tjupmmistcsr1k8k0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4_6n-v-U1Rzd0J1xHgvyvdqSaaMOiNkw',
    appId: '1:173334404915:ios:93d17190a529f62247e846',
    messagingSenderId: '173334404915',
    projectId: 'flutter-firebase-1b98d',
    storageBucket: 'flutter-firebase-1b98d.firebasestorage.app',
    iosClientId: '173334404915-3jh6inpe7r28mm6tjupmmistcsr1k8k0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHk0vOJgz66AZgSCzlA_mX3durKEMzC1w',
    appId: '1:173334404915:web:d8c9dbd61c35643747e846',
    messagingSenderId: '173334404915',
    projectId: 'flutter-firebase-1b98d',
    authDomain: 'flutter-firebase-1b98d.firebaseapp.com',
    storageBucket: 'flutter-firebase-1b98d.firebasestorage.app',
    measurementId: 'G-GM67YJJXRR',
  );
}
